baseURL = "/"
languageCode = "en-us"
title = "Durham Drives"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Durham Drives"

  [params.homepage_meta_tags]
    meta_description = "Providing transportation to and from the polls"
    meta_og_title = "Durham Drives"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"

[menu]
  [[menu.main]]
    name = "COVID-19 Guidelines"
    url = "/covid"
      weight = 1

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

